server:
  port: 5155
  servlet:
    context-path: /


spring:
  data:
    mongodb:
      uri: mongodb+srv://hatrnre:Z29kJNGoU7OKr4aa@cluster0.mpxpo5m.mongodb.net/?retryWrites=true&w=majority
      database: Olympic24