server:
  port: 5212
  servlet:
    context-path: /

spring:
  main:
    web-application-type: reactive


  cloud:
    gateway:
      routes:
        - id: calendrier-service
          uri: http://localhost:5154
          predicates:
            - Path=/api/calendrier/**
          filters:
            - RewritePath=/api/calendrier/(?<segment>.*), /${segment}
        - id: site-service
          uri: http://localhost:5153
          predicates:
            - Path=/api/sites/**
          filters:
            - RewritePath=/api/sites/(?<segment>.*), /${segment}
        - id: sport-service
          uri: http://localhost:5155
          predicates:
            - Path=/api/sports/**
          filters:
            - RewritePath=/api/sports/(?<segment>.*), /${segment}
        - id: spectateur-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/spectateur/**
          filters:
            - RewritePath=/api/spectateur/(?<segment>.*), /${segment}
    discovery:
      enabled: true

springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: calendrier-service
      paths-to-match:
        - /api/calendrier/**
      display-name: Calendrier
    - group: site-service
      paths-to-match:
        - /api/sites/**
      display-name: Sites
    - group: sport-service
      paths-to-match:
        - /api/sports/**
      display-name: Sports
    - group: spectateur-service
      paths-to-match:
        - /api/spectateur/**
      display-name: Spectateur
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: http://localhost:5212/api/sites/v3/api-docs
        name: Site
      - url: http://localhost:5212/api/sports/v3/api-docs
        name: Sport
      - url: http://localhost:5212/api/calendrier/v3/api-docs
        name: Calendrier
      - url: http://localhost:5212/api/spectateur/v3/api-docs
        name: Spectateur
