apiVersion: v1
kind: Pod
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  containers:
    - name: spring-app-container
      image: calendrier-spec:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080